*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
Server bound to 127.0.0.1:36311 (IPv4)
Extension host agent listening on 36311

[08:58:00] 




[08:58:00] Extension host agent started.
[08:58:00] [127.0.0.1][75cd5650][ManagementConnection] New connection established.
[08:58:00] [127.0.0.1][16166940][ExtensionHostConnection] New connection established.
[08:58:00] Deleted uninstalled extension from disk ms-python.python /home/pi/.vscode-server/extensions/ms-python.python-2024.2.0
[08:58:00] Deleted uninstalled extension from disk ms-python.vscode-pylance /home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2024.2.2
[08:58:01] [127.0.0.1][16166940][ExtensionHostConnection] <3389> Launched Extension Host Process.
[08:59:30] [127.0.0.1][75cd5650][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[08:59:30] [127.0.0.1][16166940][ExtensionHostConnection] <3389> Extension Host Process exited with code: 0, signal: null.
Cancelling previous shutdown timeout
[08:59:30] Cancelling previous shutdown timeout
Last EH closed, waiting before shutting down
[08:59:30] Last EH closed, waiting before shutting down
Got delay-shutdown request while in shutdown timeout, delaying
[08:59:44] Got delay-shutdown request while in shutdown timeout, delaying
Cancelling previous shutdown timeout
[08:59:44] Cancelling previous shutdown timeout
[08:59:44] [127.0.0.1][e862cf2b][ManagementConnection] New connection established.
[08:59:44] [127.0.0.1][363f71f8][ExtensionHostConnection] New connection established.
[08:59:44] [127.0.0.1][363f71f8][ExtensionHostConnection] <3664> Launched Extension Host Process.
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host
    at A.U (/home/pi/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/platform/terminal/node/ptyHostMain.js:43:32407)
    at A.updateTitle (/home/pi/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/platform/terminal/node/ptyHostMain.js:43:27539)
    at U.<computed> (/home/pi/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/platform/terminal/node/ptyHostMain.js:43:22765)
    at Object.call (/home/pi/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/platform/terminal/node/ptyHostMain.js:34:5041)
    at $.s (/home/pi/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/platform/terminal/node/ptyHostMain.js:32:5153)
    at $.q (/home/pi/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/platform/terminal/node/ptyHostMain.js:32:4662)
    at a.value (/home/pi/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/platform/terminal/node/ptyHostMain.js:32:4064)
    at d.y (/home/pi/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at d.fire (/home/pi/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process.ne (/home/pi/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/platform/terminal/node/ptyHostMain.js:25:10072)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[08:59:47] Error [CodeExpectedError]: Could not find pty on pty host
    at A.U (/home/pi/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/platform/terminal/node/ptyHostMain.js:43:32407)
    at A.updateTitle (/home/pi/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/platform/terminal/node/ptyHostMain.js:43:27539)
    at U.<computed> (/home/pi/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/platform/terminal/node/ptyHostMain.js:43:22765)
    at Object.call (/home/pi/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/platform/terminal/node/ptyHostMain.js:34:5041)
    at $.s (/home/pi/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/platform/terminal/node/ptyHostMain.js:32:5153)
    at $.q (/home/pi/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/platform/terminal/node/ptyHostMain.js:32:4662)
    at a.value (/home/pi/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/platform/terminal/node/ptyHostMain.js:32:4064)
    at d.y (/home/pi/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at d.fire (/home/pi/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process.ne (/home/pi/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/platform/terminal/node/ptyHostMain.js:25:10072)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[node.js fs] readdir with filetypes failed with error:  [Error: EACCES: permission denied, scandir '/tmp/systemd-private-26c2641d54b2419dab40bb7ce8437bb6-systemd-timesyncd.service-rk3rIi'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/tmp/systemd-private-26c2641d54b2419dab40bb7ce8437bb6-systemd-timesyncd.service-rk3rIi'
}
New EH opened, aborting shutdown
[09:04:44] New EH opened, aborting shutdown
